queue_rules:
  - name: default
    conditions:
      - check-success=detekt
      - check-success=ktlint
      - check-success=tests-ubuntu
      - check-success=tests-windows

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - check-success=detekt
      - check-success=ktlint
      - check-success=tests-ubuntu
      - check-success=tests-windows
    actions:
      queue:
        name: default
        method: squash
